[package]
name = "hello"
version = "0.1.0"
authors = ["Larry Fenske <Larry.Fenske@hpe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
[lib]
name = "foo"
crate-type = ["dylib"]
